### ISSUE TITLE
How to generate new  standard 16 x16 puzzles with and without template?

### ISSUE THREAD

**Issue by ynandwan** [bartp5/gss#2]
I wish to generate sudoku puzzles of size 16 x 16. Following the documentation, I tried to do so by running the following command:
```
./gss -g -t template16.txt
[template16.txt](https://github.com/bartp5/gss/files/4994551/template16.txt)

```
The output console says: ```Warning, sudoku has at least 11 solutions. Stopped searching for more. Found 11 solutions in 4.350900e-02s```. But I don't know where are the solutions being written?

Also, how should I go about generating random puzzles without any template while also ensuring that they have unique solutions?
I am attaching the template file that I used.

**Comment by bartp5** [comment]
Hi,

The template file you use is not a valid soduku in that it has many solutions. If you do not have a valid sudoku puzzle you can let gss fill in the sudoku with the '-f' switch. Try:
gss -t template16.txt -f
This will give you a solved sudoku. If you want to directly generate a puzzle, do:
gss -t template16.txt -f -g <level>
where <level> is the logic level.
As with the the template you are using, gss generates an input file for asymptote, you probably want to save the results to files instead of dumping everything to stdout:
gss -t template16.txt -f -g <level> -p puzzle.asy -s solution.asy

It seems you are trying to make a sort of 16x16 NRC-like sudoku with 9 extra blocks. It is a nice variation. To finish that you would need to add the 9 custom blocks. I would use the \<matrix\> tag for that, like in the attached file:
[template16.txt](https://github.com/bartp5/gss/files/4995181/template16.txt)
(note that after the \<matrix\>tag only the numbers and dots are processed, all other characters I only added so that I understand what I am doing)
Using gss on the attached template gives me puzzles and solutions like so: 
![puzzle](https://user-images.githubusercontent.com/2051341/88809272-3747eb00-d1b4-11ea-954b-62b1d6e764db.png)
![solution](https://user-images.githubusercontent.com/2051341/88809284-39aa4500-d1b4-11ea-8301-b1ee30c70181.png)




Cheers

**Comment by ynandwan** [comment]
Thanks! The template file you provided is useful. 

Cheers,
